repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.51.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
      args: ['--args=--sort-by required --indent 3 --lockfile=false']
    - id: terraform_validate
    - id: terraform_tflint
