name: 'Create invalidation on CloudFront'

on:
  workflow_dispatch:
    inputs:
      networkName:
        description: 'Enter the network name'
        required: true
        type: string
      region:
        description: 'Enter the region'
        required: true
        type: string
      
env:
  CICD_DEPLOYMENT_TOKEN: ${{ secrets.CICD_DEPLOYMENT_TOKEN }}

  NETWORK_NAME: ${{ inputs.networkName }}

  AWS_REGION: ${{ github.event.inputs.region }}

  AWS_IAM_ROLE_ARN_TO_ASSUME: ${{ vars.AWS_IAM_ROLE_ARN_TO_ASSUME }}
  
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  createInvalidation:
    name: 'Create invalidation on CloudFront'
    runs-on: ubuntu-22.04 # version: 20230911.1.0
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3.3.0
        with:
          token: ${{ env.CICD_DEPLOYMENT_TOKEN }}
      
      - name: 'Configure AWS Credentials Action For GitHub Actions'
        uses: aws-actions/configure-aws-credentials@v3.0.2
        with:
          role-to-assume: ${{ env.AWS_IAM_ROLE_ARN_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 'Set env variables'
        run: |
          DISTRIBUTION=$(ls "private/${{ env.NETWORK_NAME }}/LWA/" | head -n 1)
          echo "DISTRIBUTION_ID=$(aws cloudfront list-distributions --output json | jq -r '.DistributionList.Items[] | select(.Comment == "'$DISTRIBUTION'") | .Id')" >> $GITHUB_ENV
          
          echo $DISTRIBUTION

      - name: 'Create Invalidation'
        run: |
          if [[ ! -z "$DISTRIBUTION_ID" ]]; then
            echo "Found CloudFront Distribution ID: $DISTRIBUTION_ID"
            aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'
          else
            echo "Error: Could not find CloudFront Distribution ID."
            exit 1
          fi
